import type { ResourceCategory } from './types';

/**
 * Muted tints: the pictogram names the commodity, so resource colours stay quiet next to the
 * vermilion events, the religious palette and the amber reserved for selection (see
 * lib/colors/semantic.ts). Oil is a dark brown drop; gas a pale blue-grey flame.
 */
export const RESOURCE_COLORS: Record<ResourceCategory, string> = {
  oil: '#78573f',
  gas: '#9accdb',
  coal: '#b3b9c5',
  uranium: '#bdbfa5',
  iron: '#ddb2a7',
  copper: '#cfac98',
  gold: '#d8d5cf',
  lithium: '#acd7c5',
  'rare-earths': '#baabca',
  bauxite: '#dcb5a4',
  nickel: '#a1b89c',
  phosphate: '#a5b0d1',
  silver: '#cbd8de',
  tin: '#accfca',
  salt: '#dcd6d0',
  zinc: '#add1da',
  lead: '#aab3ce',
  cobalt: '#a4b0d1',
  manganese: '#dfbbd2',
  molybdenum: '#b8cbd4',
  graphite: '#bac2c8',
  diamond: '#c1eae9',
  potash: '#e7bfce',
  platinum: '#dfd7d1',
  palladium: '#bfded4',
  tungsten: '#d1cbc2',
  antimony: '#afc6e4',
  niobium: '#b8abcb',
  tantalum: '#aecdda',
  mercury: '#d0d9e7',
  barium: '#e2c6ce',
  chromium: '#b6d9d4',
  boron: '#cadab9',
  vanadium: '#aec2e2',
  fluorite: '#c3b4d4',
  'mineral-sands': '#cfc8be',
  'platinum-group': '#bebea7',
  titanium: '#b9cfdf',
  silicon: '#afced9',
  magnesium: '#dddbd6',
  cesium: '#c3bbdc',
  scandium: '#ccc4b9',
  selenium: '#d5ac9e',
  tellurium: '#bbd3ca',
  indium: '#b4cde8',
};
